name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Sovren.SDK/Sovren.SDK.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/Sovren.SDK/Sovren.SDK.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Release src/Sovren.SDK/Sovren.SDK.csproj --output .
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_API_KEY}} --skip-duplicate
      
